### PR TITLE
new ecommerce report

### PR DESCRIPTION
**Pull request by HakkiKaanSimsek**

### CODE REVIEW

**Comment by lanthias** [comment]
Thanks Kaan! Just a few remaining things:
- `full_width` should actually be on the `dp.Report` constructor and not the `publish` method
- a few of the plotly plots have defined width and height which causes them to scroll on different screen sizes as they lose responsiveness - these can be removed and they should be automatically responsive
- could you make the prophet plotly plots responsive? i see internally in the library it sets width and height on the figure, but it should be possible to override this

Looking awesome!

**Comment by HakkiKaanSimsek** [comment]
@lanthias Thank you for your feedback.

- full_width added to dp.Report
- width and height removed from plots
- adjusted prophet plots like others

The problem is probably in your local because the data you share above is Netflix stock price, not superstore data.

**Comment by lanthias** [comment]
Thanks Kaan! For the prophet plots I actually meant just remove the width to make them totally responsive - you can do this as follows:
```
fig12.update_layout(autosize=True, width=None)
```

Let's also put two markdown headings for each section, as follows:

```
dp.Report(
    "# Data exploration",
    dp.Blocks(
        dp.Plot(fig0, caption='This plot shows total sales by day from 2014 to 2017.'), 
        dp.Plot(fig1, caption='This plot shows total profit by year, month, day of week, day of month.'), 
        dp.Plot(fig2, caption='This plot shows total sales by consumer, corporate, home-office segments.'), 
        dp.Plot(fig3, caption='This plot shows total profit by consumer, corporate, home-office segments.'), 
        dp.Plot(fig4, caption='This plot shows total sales by west, east, central, south regions.'), 
        dp.Plot(fig5, caption='This plot shows total profit by west, east, central, south regions.'), 
        dp.Plot(fig6, caption='This plot shows total sales by category.'), 
        dp.Plot(fig7, caption='This plot shows total profit by sub-category.'),
        dp.Plot(fig8, caption='This plot shows total sales by category.'),
        dp.Plot(fig9, caption='This plot shows total profit by sub-category.'),
        dp.Plot(fig10, caption='This plot shows total sales by city.'),
        dp.Plot(fig11, caption='This plot shows total profit by city.'),
        columns=2,
        rows=6
    ), 
    "# Forecasting",
    dp.Plot(fig12, caption='This plot shows daily profit forecasting using fbprophet.'),
      dp.Plot(fig13, caption='This plot shows trend, yearly seasonality, and weekly seasonality of the time series.'),
    full_width=True
)
```

Then we're good to merge :+1:

**Comment by HakkiKaanSimsek** [comment]
Thanks, Leo! I removed the width and added markdown headings for each section. I pushed changes in the last commit.

**Pull request merged**
